<?php
// Auto-generated by Module_manager — do not edit manually.
if (! defined("BASEPATH")) exit("No direct script access allowed");

require_once __DIR__ . "/__originals/Mine.php";

class Mine extends Mine__real
{
    public function index()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "index", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::index", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::index();
        module_controller_hook("after::Mine::index", $ctx);
        return $ctx["result"];
    }

    public function sair()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "sair", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::sair", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::sair();
        module_controller_hook("after::Mine::sair", $ctx);
        return $ctx["result"];
    }

    public function resetarSenha()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "resetarSenha", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::resetarSenha", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::resetarSenha();
        module_controller_hook("after::Mine::resetarSenha", $ctx);
        return $ctx["result"];
    }

    public function senhaSalvar()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "senhaSalvar", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::senhaSalvar", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::senhaSalvar();
        module_controller_hook("after::Mine::senhaSalvar", $ctx);
        return $ctx["result"];
    }

    public function tokenManual()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "tokenManual", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::tokenManual", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::tokenManual();
        module_controller_hook("after::Mine::tokenManual", $ctx);
        return $ctx["result"];
    }

    public function verifyTokenSenha()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "verifyTokenSenha", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::verifyTokenSenha", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::verifyTokenSenha();
        module_controller_hook("after::Mine::verifyTokenSenha", $ctx);
        return $ctx["result"];
    }

    public function gerarTokenResetarSenha()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "gerarTokenResetarSenha", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::gerarTokenResetarSenha", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::gerarTokenResetarSenha();
        module_controller_hook("after::Mine::gerarTokenResetarSenha", $ctx);
        return $ctx["result"];
    }

    public function login()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "login", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::login", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::login();
        module_controller_hook("after::Mine::login", $ctx);
        return $ctx["result"];
    }

    public function painel()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "painel", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::painel", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::painel();
        module_controller_hook("after::Mine::painel", $ctx);
        return $ctx["result"];
    }

    public function conta()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "conta", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::conta", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::conta();
        module_controller_hook("after::Mine::conta", $ctx);
        return $ctx["result"];
    }

    public function editarDados()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "editarDados", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::editarDados", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::editarDados();
        module_controller_hook("after::Mine::editarDados", $ctx);
        return $ctx["result"];
    }

    public function compras()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "compras", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::compras", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::compras();
        module_controller_hook("after::Mine::compras", $ctx);
        return $ctx["result"];
    }

    public function cobrancas()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "cobrancas", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::cobrancas", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::cobrancas();
        module_controller_hook("after::Mine::cobrancas", $ctx);
        return $ctx["result"];
    }

    public function atualizarcobranca($id = null)
    {
        $args = [$id];
        $ctx  = ["controller" => "Mine", "method" => "atualizarcobranca", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::atualizarcobranca", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::atualizarcobranca(...$args);
        module_controller_hook("after::Mine::atualizarcobranca", $ctx);
        return $ctx["result"];
    }

    public function enviarcobranca()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "enviarcobranca", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::enviarcobranca", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::enviarcobranca();
        module_controller_hook("after::Mine::enviarcobranca", $ctx);
        return $ctx["result"];
    }

    public function os()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "os", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::os", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::os();
        module_controller_hook("after::Mine::os", $ctx);
        return $ctx["result"];
    }

    public function visualizarOs($id = null)
    {
        $args = [$id];
        $ctx  = ["controller" => "Mine", "method" => "visualizarOs", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::visualizarOs", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::visualizarOs(...$args);
        module_controller_hook("after::Mine::visualizarOs", $ctx);
        return $ctx["result"];
    }

    public function validarCPF($cpf)
    {
        $args = [$cpf];
        $ctx  = ["controller" => "Mine", "method" => "validarCPF", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::validarCPF", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::validarCPF(...$args);
        module_controller_hook("after::Mine::validarCPF", $ctx);
        return $ctx["result"];
    }

    public function validarCNPJ($cnpj)
    {
        $args = [$cnpj];
        $ctx  = ["controller" => "Mine", "method" => "validarCNPJ", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::validarCNPJ", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::validarCNPJ(...$args);
        module_controller_hook("after::Mine::validarCNPJ", $ctx);
        return $ctx["result"];
    }

    public function formatarChave($chave)
    {
        $args = [$chave];
        $ctx  = ["controller" => "Mine", "method" => "formatarChave", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::formatarChave", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::formatarChave(...$args);
        module_controller_hook("after::Mine::formatarChave", $ctx);
        return $ctx["result"];
    }

    public function gerarPagamentoGerencianetBoleto()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "gerarPagamentoGerencianetBoleto", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::gerarPagamentoGerencianetBoleto", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::gerarPagamentoGerencianetBoleto();
        module_controller_hook("after::Mine::gerarPagamentoGerencianetBoleto", $ctx);
        return $ctx["result"];
    }

    public function gerarPagamentoGerencianetLink()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "gerarPagamentoGerencianetLink", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::gerarPagamentoGerencianetLink", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::gerarPagamentoGerencianetLink();
        module_controller_hook("after::Mine::gerarPagamentoGerencianetLink", $ctx);
        return $ctx["result"];
    }

    public function imprimirOs($id = null)
    {
        $args = [$id];
        $ctx  = ["controller" => "Mine", "method" => "imprimirOs", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::imprimirOs", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::imprimirOs(...$args);
        module_controller_hook("after::Mine::imprimirOs", $ctx);
        return $ctx["result"];
    }

    public function visualizarCompra($id = null)
    {
        $args = [$id];
        $ctx  = ["controller" => "Mine", "method" => "visualizarCompra", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::visualizarCompra", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::visualizarCompra(...$args);
        module_controller_hook("after::Mine::visualizarCompra", $ctx);
        return $ctx["result"];
    }

    public function imprimirCompra($id = null)
    {
        $args = [$id];
        $ctx  = ["controller" => "Mine", "method" => "imprimirCompra", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::imprimirCompra", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::imprimirCompra(...$args);
        module_controller_hook("after::Mine::imprimirCompra", $ctx);
        return $ctx["result"];
    }

    public function minha_ordem_de_servico($y = null, $when = null)
    {
        $args = [$y, $when];
        $ctx  = ["controller" => "Mine", "method" => "minha_ordem_de_servico", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::minha_ordem_de_servico", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::minha_ordem_de_servico(...$args);
        module_controller_hook("after::Mine::minha_ordem_de_servico", $ctx);
        return $ctx["result"];
    }

    public function adicionarOs()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "adicionarOs", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::adicionarOs", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::adicionarOs();
        module_controller_hook("after::Mine::adicionarOs", $ctx);
        return $ctx["result"];
    }

    public function detalhesOs($id = null)
    {
        $args = [$id];
        $ctx  = ["controller" => "Mine", "method" => "detalhesOs", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::detalhesOs", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::detalhesOs(...$args);
        module_controller_hook("after::Mine::detalhesOs", $ctx);
        return $ctx["result"];
    }

    public function cadastrar()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "cadastrar", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::cadastrar", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::cadastrar();
        module_controller_hook("after::Mine::cadastrar", $ctx);
        return $ctx["result"];
    }

    public function downloadanexo($id = null)
    {
        $args = [$id];
        $ctx  = ["controller" => "Mine", "method" => "downloadanexo", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::downloadanexo", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::downloadanexo(...$args);
        module_controller_hook("after::Mine::downloadanexo", $ctx);
        return $ctx["result"];
    }

    public function captcha()
    {
        $args = [];
        $ctx  = ["controller" => "Mine", "method" => "captcha", "args" => &$args, "result" => null];
        module_controller_hook("before::Mine::captcha", $ctx);
        if (! empty($ctx["abort"])) {
            if (isset($ctx["response"])) echo $ctx["response"];
            return;
        }
        $ctx["result"] = parent::captcha();
        module_controller_hook("after::Mine::captcha", $ctx);
        return $ctx["result"];
    }

}
