<?php

if (! defined('BASEPATH')) {
    exit('No direct script access allowed');
}

/**
 * pre_system: garante que proxies de controllers e wrappers de módulos estejam
 * em application/controllers/ antes do Router fazer a checagem de arquivos.
 *
 * É a via primária de geração quando o install() consegue escrever no diretório,
 * e a via de recuperação quando não conseguiu (ex: permissão restaurada depois).
 *
 * Roda sem CI nem DB — opera apenas com o filesystem.
 */
function ensure_module_wrappers()
{
    $modulesPath = FCPATH . 'modules/';
    if (! is_dir($modulesPath)) {
        return;
    }

    foreach (scandir($modulesPath) as $slug) {
        if ($slug === '.' || $slug === '..' || strncmp($slug, 'tmp_', 4) === 0) {
            continue;
        }

        $modulePath = $modulesPath . $slug . '/';
        if (! is_dir($modulePath) || ! file_exists($modulePath . 'module.json')) {
            continue;
        }

        // ── Wrappers finos para controllers/models do próprio módulo ──────────
        foreach (['controllers', 'models'] as $type) {
            $srcDir = $modulePath . $type . '/';
            if (! is_dir($srcDir)) {
                continue;
            }
            foreach (glob($srcDir . '*.php') ?: [] as $src) {
                $filename = basename($src);
                $dest     = APPPATH . $type . '/' . $filename;
                if (! file_exists($dest)) {
                    @file_put_contents(
                        $dest,
                        "<?php\nif (!defined('BASEPATH')) exit('No direct script access allowed');\nrequire_once FCPATH . 'modules/{$slug}/{$type}/{$filename}';\n"
                    );
                }
            }
        }

        // ── Proxies para controllers hookados pelo módulo ─────────────────────
        $hookFile = $modulePath . 'hooks/module_hooks.php';
        if (! file_exists($hookFile)) {
            continue;
        }

        $moduleControllerHooks = [];
        include $hookFile;

        $controllers = [];
        foreach (array_keys($moduleControllerHooks) as $hookName) {
            if (preg_match('/^(?:before|after)::([A-Za-z][A-Za-z0-9_]*)::/', $hookName, $m)) {
                $controllers[] = $m[1];
            }
        }

        foreach (array_unique($controllers) as $className) {
            _ensure_controller_proxy($className);
        }
    }
}

/**
 * Gera o arquivo proxy para um controller se ainda não existir.
 * Idêntico à lógica de Module_manager::generateControllerProxy() mas sem CI.
 */
function _ensure_controller_proxy(string $className): void
{
    $controllerFile = APPPATH . 'controllers/' . $className . '.php';
    $originalsDir   = APPPATH . 'controllers/__originals/';
    $originalBak    = $originalsDir . $className . '.php';

    if (! file_exists($controllerFile)) {
        return;
    }

    $src = file_get_contents($controllerFile);

    // Proxy ja existe e o controller atual e o proxy (nao o original)
    if (file_exists($originalBak) && strpos($src, 'Auto-generated by Module_manager') !== false) {
        return;
    }

    // Não proxia infraestrutura do sistema de módulos
    if (
        strpos($src, 'Auto-generated by Module_manager') !== false
        || strpos($src, '__real') !== false
        || strpos($src, 'Module_dispatch') !== false
    ) {
        return;
    }

    if (! is_dir($originalsDir) && ! @mkdir($originalsDir, 0755, true)) {
        return;
    }

    // Salva original com classe renomeada para Foo__real
    $realSrc = preg_replace(
        '/\bclass\s+' . preg_quote($className, '/') . '\b/',
        'class ' . $className . '__real',
        $src
    );
    if (@file_put_contents($originalBak, $realSrc) === false) {
        return;
    }

    // Extrai metodos publicos nao-magicos com assinatura completa
    preg_match_all(
        '/public\s+function\s+([a-zA-Z][a-zA-Z0-9_]*)\s*\(([^)]*)\)/',
        $src,
        $matches,
        PREG_SET_ORDER
    );

    $lines   = [];
    $lines[] = '<?php';
    $lines[] = '// Auto-generated by Module_manager — do not edit manually.';
    $lines[] = "if (! defined('BASEPATH')) exit('No direct script access allowed');";
    $lines[] = '';
    $lines[] = "require_once __DIR__ . '/__originals/{$className}.php';";
    $lines[] = '';
    $lines[] = "class {$className} extends {$className}__real";
    $lines[] = '{';

    foreach ($matches as $m) {
        $method = $m[1];
        $params = trim($m[2]);

        // extrai nomes das variaveis para passar ao parent
        $argNames = [];
        if ($params !== '') {
            foreach (explode(',', $params) as $p) {
                if (preg_match('/(\$\w+)\s*(?:=.*)?$/', trim($p), $am)) {
                    $argNames[] = $am[1];
                }
            }
        }
        $callArgs = implode(', ', $argNames);
        $argsInit = $callArgs ? "        \$args = [{$callArgs}];" : '        $args = [];';
        $callExpr = $callArgs
            ? "        \$ctx['result'] = parent::{$method}(...\$args);"
            : "        \$ctx['result'] = parent::{$method}();";

        $lines[] = "    public function {$method}({$params})";
        $lines[] = '    {';
        $lines[] = $argsInit;
        $lines[] = "        \$ctx  = ['controller' => '{$className}', 'method' => '{$method}', 'args' => &\$args, 'result' => null];";
        $lines[] = "        module_controller_hook('before::{$className}::{$method}', \$ctx);";
        $lines[] = "        if (! empty(\$ctx['abort'])) {";
        $lines[] = "            if (isset(\$ctx['response'])) echo \$ctx['response'];";
        $lines[] = '            return;';
        $lines[] = '        }';
        $lines[] = $callExpr;
        $lines[] = "        module_controller_hook('after::{$className}::{$method}', \$ctx);";
        $lines[] = "        return \$ctx['result'];";
        $lines[] = '    }';
        $lines[] = '';
    }

    $lines[] = '}';

    @file_put_contents($controllerFile, implode("\n", $lines) . "\n");
}

/**
 * pre_controller: fallback para quando nem wrapper nem proxy existem.
 * Tenta require_once do controller do módulo diretamente e informa o Router.
 */
function load_module_controller()
{
    $RTR = &load_class('Router', 'core');
    $URI = &load_class('URI', 'core');

    $segments = $URI->segments;
    if (empty($segments)) {
        return;
    }

    $slug      = strtolower($segments[1]);
    $ctrlClass = ucfirst($slug);

    if (class_exists($ctrlClass, false)) {
        return;
    }

    $ctrlFile = FCPATH . 'modules/' . $slug . '/controllers/' . $ctrlClass . '.php';
    if (! file_exists($ctrlFile)) {
        return;
    }

    require_once $ctrlFile;

    $RTR->set_class($ctrlClass);
    $RTR->set_method(isset($segments[2]) ? $segments[2] : 'index');
}
